name: slrtce
description: A new Flutter project for the student Career Campus Portal with hybrid backend firebase and supabase. 
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  # google_sign_in: ^6.2.1     # upcomming google sign up features
  
  #supabase dependencies for storage 
  supabase_flutter: ^2.3.4

  # Other dependencies
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  file_picker: ^8.0.0
  flutter_image_compress: ^2.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/icons/
    - assets/images/